name: Demo 1 - Deploy Simple Function App

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'functions/demo1-simple/**'
      - 'terraform/demo1/**'
      - '.github/workflows/demo1-function.yml'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'func-mms-demo1'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './functions/demo1-simple'
  TERRAFORM_VERSION: '1.5.0'

jobs:
  terraform:
    name: 'Deploy Infrastructure with Terraform'
    runs-on: ubuntu-latest
    environment: development
    
    defaults:
      run:
        shell: bash
        working-directory: ./terraform/demo1

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -no-color -input=false
      continue-on-error: true

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve -input=false

  deploy:
    name: 'Deploy Function App'
    runs-on: ubuntu-latest
    needs: terraform
    if: github.ref == 'refs/heads/main'
    environment: development

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

    - name: 'Test Function Endpoint'
      run: |
        echo "Waiting for function to be ready..."
        sleep 30
        
        FUNCTION_URL="https://${{ env.AZURE_FUNCTIONAPP_NAME }}.azurewebsites.net/api/HttpTrigger"
        
        echo "Testing function at: $FUNCTION_URL"
        
        # Test without name parameter
        echo "Test 1: Default response"
        curl -f "$FUNCTION_URL" || echo "Test 1 failed"
        
        # Test with name parameter
        echo "Test 2: With name parameter"
        curl -f "$FUNCTION_URL?name=MMS-Attendee" || echo "Test 2 failed"
        
        echo "Demo 1 function deployment and testing completed!"